# Generated by Django 4.2.20 on 2025-12-07 13:26

import django.db.models.deletion
import django.utils.timezone
import rules.contrib.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0046_alter_invitationtogroup_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "start_datetime",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Start"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="End"),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "abstract": False,
                "default_permissions": (
                    "add_global",
                    "change_global",
                    "view_global",
                    "delete_global",
                    "list_global",
                    "view",
                ),
            },
            bases=(models.Model, rules.contrib.models.RulesModelMixin),
        ),
        migrations.CreateModel(
            name="RepeatedEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="calendarevents.event",
                    ),
                ),
                ("repeat", models.BooleanField(default=False, verbose_name="Repeat")),
                (
                    "repeat_interval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Biweekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=10,
                        verbose_name="Repeat Interval",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repeated Event",
                "verbose_name_plural": "Repeated Events",
                "abstract": False,
                "default_permissions": (
                    "add_global",
                    "change_global",
                    "view_global",
                    "delete_global",
                    "list_global",
                    "view",
                ),
            },
            bases=("calendarevents.event",),
        ),
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "visibility_group",
                    models.ManyToManyField(
                        blank=True,
                        related_name="visible_calendars_group",
                        to="members.group",
                        verbose_name="Visible to groups",
                    ),
                ),
                (
                    "visibility_member",
                    models.ManyToManyField(
                        blank=True,
                        related_name="visible_calendars_member",
                        to="members.member",
                        verbose_name="Visible to members",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar",
                "verbose_name_plural": "Calendars",
                "abstract": False,
                "default_permissions": (
                    "add_global",
                    "change_global",
                    "view_global",
                    "delete_global",
                    "list_global",
                    "view",
                ),
            },
            bases=(models.Model, rules.contrib.models.RulesModelMixin),
        ),
        migrations.CreateModel(
            name="ManualEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="calendarevents.event",
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_events",
                        to="calendarevents.calendar",
                        verbose_name="Calendar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual Event",
                "verbose_name_plural": "Manual Events",
                "abstract": False,
                "default_permissions": (
                    "add_global",
                    "change_global",
                    "view_global",
                    "delete_global",
                    "list_global",
                    "view",
                ),
            },
            bases=("calendarevents.event",),
        ),
    ]
