# Generated by Django 4.0.1 on 2024-12-26 09:45

from django.db import migrations
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_bill_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='proof',
            field=utils.RestrictedFileField(blank=True, upload_to='bill_images', verbose_name='Proof'),
        ),
    ]
