# Generated by Django 4.0.1 on 2025-01-18 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_member_upload_registration_form_key'),
        ('members', '0033_freizeit_approved_extra_youth_leader_count'),
        ('finance', '0005_alter_bill_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='allowance_to',
            field=models.ManyToManyField(help_text='The youth leaders to which an allowance should be paid. The count must match the number of permitted youth leaders.', related_name='receives_allowance_for_statements', to='members.Member', verbose_name='Pay allowance to'),
        ),
        migrations.AddField(
            model_name='statement',
            name='subsidy_to',
            field=models.ForeignKey(help_text='The person that should receive the subsidy for night and travel costs. Typically the person who paid for them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receives_subsidy_for_statements', to='members.member', verbose_name='Pay subsidy to'),
        ),
    ]
