# Generated by Django 4.0.1 on 2025-01-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_freizeit_approved_extra_youth_leader_count'),
        ('finance', '0006_statement_add_allowance_to_subsidy_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='allowance_to',
            field=models.ManyToManyField(blank=True, help_text='The youth leaders to which an allowance should be paid. The count must match the number of permitted youth leaders.', related_name='receives_allowance_for_statements', to='members.Member', verbose_name='Pay allowance to'),
        ),
    ]
