# Generated by Django 4.0.1 on 2025-01-23 22:16

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0033_freizeit_approved_extra_youth_leader_count"),
        ("finance", "0007_alter_statement_allowance_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statement",
            name="allowance_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="The youth leaders to which an allowance should be paid.",
                related_name="receives_allowance_for_statements",
                to="members.Member",
                verbose_name="Pay allowance to",
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="subsidy_to",
            field=models.ForeignKey(
                blank=True,
                help_text="The person that should receive the subsidy for night and travel costs. Typically the person who paid for them.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receives_subsidy_for_statements",
                to="members.member",
                verbose_name="Pay subsidy to",
            ),
        ),
    ]
