# Generated by Django 4.2.20 on 2025-04-03 21:04

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0039_membertraining_certificate_attendance"),
        ("finance", "0008_alter_statement_allowance_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="ljp_to",
            field=models.ForeignKey(
                blank=True,
                help_text="The person that should receive the ljp contributions for the participants. Should be only selected if an ljp request was submitted.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receives_ljp_for_statements",
                to="members.member",
                verbose_name="Pay ljp contributions to",
            ),
        ),
    ]
