# Generated by Django 4.2.20 on 2025-10-11 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_statement_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statement",
            name="confirmed",
        ),
        migrations.RemoveField(
            model_name="statement",
            name="submitted",
        ),
    ]
