# Generated by Django 4.2.20 on 2026-04-26 13:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0013_statement_settings_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillGenerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "rule",
                    models.JSONField(
                        blank=True,
                        help_text="Rule generating expenses from the input parameters of this statement.",
                        verbose_name="Rule",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="statement",
            name="night_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Laut Preisliste für eine*n Jugendleiter*in. Angabe wird benötigt für die Berechnung von Zuschüssen aus dem Jugendetat. Maximaler Zuschuss pro Person und Nacht: 11 €",
                max_digits=5,
                verbose_name="Price per night",
            ),
        ),
        migrations.AlterField(
            model_name="statement",
            name="short_description",
            field=models.CharField(max_length=30, verbose_name="Short description"),
        ),
        migrations.AlterField(
            model_name="statement",
            name="status",
            field=models.IntegerField(
                choices=[(0, "In preparation"), (1, "Submitted"), (2, "Completed")],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="AutomaticBillConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "generators",
                    models.ManyToManyField(
                        to="finance.billgenerator", verbose_name="Bill generators"
                    ),
                ),
            ],
        ),
    ]
