# Generated by Django 4.2.20 on 2026-04-26 15:46

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0014_billgenerator_alter_statement_night_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billgenerator",
            name="rule",
            field=models.TextField(
                blank=True,
                help_text="Rule generating expenses from the input parameters of this statement.",
                verbose_name="Rule",
            ),
        ),
    ]
