# Generated by Django 4.2.20 on 2026-04-26 21:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0015_alter_billgenerator_rule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billgenerator",
            options={
                "verbose_name": "Bill generation rule",
                "verbose_name_plural": "Bill generation rules",
            },
        ),
        migrations.AddField(
            model_name="statement",
            name="auto_bill_config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finance.automaticbillconfiguration",
            ),
        ),
        migrations.CreateModel(
            name="GeneratedBill",
            fields=[
                (
                    "bill_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="finance.bill",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Generated at"
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.billgenerator",
                        verbose_name="Generated by rule",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (
                    "add_global",
                    "change_global",
                    "view_global",
                    "delete_global",
                    "list_global",
                    "view",
                ),
            },
            bases=("finance.bill",),
        ),
    ]
