# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mailer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', mailer.models.RestrictedFileField(blank=True, upload_to='attachments', verbose_name='file')),
            ],
            options={
                'verbose_name_plural': 'attachments',
                'verbose_name': 'attachment',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='subject')),
                ('content', models.TextField(verbose_name='content')),
                ('sent', models.BooleanField(default=False, verbose_name='sent')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='members.Member', verbose_name='reply to')),
                ('to_groups', models.ManyToManyField(blank=True, to='members.Group', verbose_name='to group')),
                ('to_memberlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.MemberList', verbose_name='to member list')),
                ('to_members', models.ManyToManyField(blank=True, to='members.Member', verbose_name='to member')),
            ],
            options={
                'verbose_name_plural': 'messages',
                'permissions': (('submit_mails', 'Can submit mails'),),
                'verbose_name': 'message',
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='msg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.Message'),
        ),
    ]
