# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-15 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20190615_1224'),
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ManyToManyField(blank=True, related_name='reply_to', to='members.Member', verbose_name='reply to'),
        ),
    ]
