# Generated by Django 4.0.1 on 2023-04-02 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_rename_permissions'),
        ('mailer', '0001_initial_squashed_0006_auto_20210924_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_messages', to='members.member', verbose_name='Created by'),
        ),
    ]
