# Generated by Django 4.0.1 on 2023-04-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_message_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'default_permissions': ('add_global', 'change_global', 'view_global', 'delete_global', 'list_global', 'view'), 'permissions': (('submit_mails', 'Can submit mails'),), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
