# Generated by Django 4.0.1 on 2024-11-17 23:31

from django.db import migrations
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='f',
            field=utils.RestrictedFileField(upload_to='attachments', verbose_name='file'),
        ),
    ]
