# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-24 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200924_1512'),
        ('mailer', '0003_emailaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reply_to',
            field=models.ManyToManyField(blank=True, related_name='reply_to', to='members.Member', verbose_name='reply to participant'),
        ),
    ]
