# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-24 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200924_1512'),
        ('mailer', '0004_auto_20200924_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='to_members',
            field=models.ManyToManyField(blank=True, to='members.Member', verbose_name='Forward to participants'),
        ),
    ]
