# Generated by Django 4.0.1 on 2024-11-23 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_alter_attachment_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z._-]*$', 'Only alphanumeric characters, ., - and _ are allowed')], verbose_name='name'),
        ),
    ]
