# Generated by Django 4.0.1 on 2024-12-01 15:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0029_alter_member_gender_alter_memberwaitinglist_gender"),
        ("mailer", "0005_alter_emailaddress_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaddress",
            name="allowed_senders",
            field=models.ManyToManyField(
                blank=True,
                help_text="Only forward e-mails of members of selected groups. Leave empty to allow all senders.",
                related_name="allowed_sender_on_emailaddresses",
                to="members.Group",
                verbose_name="Allowed sender",
            ),
        ),
    ]
