# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-24 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20210924_1155'),
        ('mailer', '0005_auto_20200924_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='to_memberlist',
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='to_groups',
            field=models.ManyToManyField(blank=True, to='members.Group', verbose_name='Forward to group'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to_email_address',
            field=models.ManyToManyField(blank=True, related_name='reply_to_email_addr', to='mailer.EmailAddress', verbose_name='reply to custom email address'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_freizeit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Freizeit', verbose_name='to freizeit'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_notelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.MemberNoteList', verbose_name='to notes list'),
        ),
    ]
