# Generated by Django 4.0.1 on 2024-12-01 17:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("mailer", "0006_emailaddress_allowed_senders"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaddress",
            name="internal_only",
            field=models.BooleanField(
                default=False,
                help_text="Only allow forwarding to this e-mail address from the internal domain.",
                verbose_name="Restrict to internal email addresses",
            ),
        ),
    ]
