# Generated by Django 4.0.1 on 2024-12-03 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_emailaddress_internal_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z._-]*$', 'Only alphanumeric characters, ., - and _ are allowed')], verbose_name='name'),
        ),
    ]
