# Generated by Django 5.1.15 on 2026-05-03 22:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("mailer", "0008_alter_emailaddress_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaddress",
            name="external_email",
            field=models.EmailField(
                blank=True,
                help_text="Set this to an arbitrary external email address. No forwarding happens for external email addresses; forwarding fields (participants, groups) must be left empty.",
                max_length=254,
                verbose_name="external email address",
            ),
        ),
        migrations.AlterField(
            model_name="emailaddress",
            name="internal_only",
            field=models.BooleanField(
                default=False,
                help_text="Leite nur E-Mails weiter, die von einer der folgenden Domains verschickt wurden: example.org.",
                verbose_name="Restrict to internal email addresses",
            ),
        ),
    ]
