# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-23 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Gruppen',
                'verbose_name': 'Gruppe',
            },
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('start_date', models.DateField(verbose_name='Von')),
                ('end_date', models.DateField(verbose_name='Bis')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ludwigsburgalpin.Group', verbose_name='Gruppe')),
            ],
            options={
                'verbose_name_plural': 'Termine',
                'verbose_name': 'Termin',
            },
        ),
    ]
