# Generated by Django 4.0.1 on 2023-03-29 20:40

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    replaces = [
        ("ludwigsburgalpin", "0001_initial"),
        ("ludwigsburgalpin", "0002_auto_20190926_1432"),
        ("ludwigsburgalpin", "0003_auto_20190926_1749"),
        ("ludwigsburgalpin", "0004_alter_termin_id"),
        ("ludwigsburgalpin", "0005_alter_termin_id"),
        ("ludwigsburgalpin", "0006_termin_anforderung_dauer_termin_anforderung_hoehe_and_more"),
        ("ludwigsburgalpin", "0007_alter_termin_group"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Termin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titel")),
                ("start_date", models.DateField(verbose_name="Von")),
                ("end_date", models.DateField(verbose_name="Bis")),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("ASG", "Alpinsportgruppe"),
                            ("OGB", "Ortsgruppe Bietigheim"),
                            ("OGV", "Ortsgruppe Vaihingen"),
                            ("JUG", "Jugend"),
                            ("FAM", "Familie"),
                            ("Ü30", "Ü30"),
                            ("MTB", "Mountainbike"),
                            ("RA", "RegioAktiv"),
                            ("SEK", "Sektion"),
                        ],
                        max_length=100,
                        verbose_name="Gruppe",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Beschreibung")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Telefonnumer")),
                ("responsible", models.CharField(max_length=100, verbose_name="Organisator")),
                (
                    "anforderung_dauer",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Etappendauer in Stunden",
                    ),
                ),
                (
                    "anforderung_hoehe",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Höhenmeter in Meter",
                    ),
                ),
                (
                    "anforderung_strecke",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Strecke in Kilometer",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WAN", "Wandern"),
                            ("BW", "Bergwandern"),
                            ("KST", "Klettersteig"),
                            ("KL", "Klettern"),
                            ("SKI", "Piste, Loipe"),
                            ("SCH", "Schneeschuhgehen"),
                            ("ST", "Skitour"),
                            ("STH", "Skihochtour"),
                            ("HT", "Hochtour"),
                            ("MTB", "Montainbike"),
                            ("AUS", "Ausbildung"),
                            ("SON", "Sonstiges z.B. Treffen"),
                        ],
                        default="SON",
                        max_length=100,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("gering", "gering"),
                            ("mittel", "mittel"),
                            ("groß", "groß"),
                            ("sehr groß", "sehr groß"),
                        ],
                        default="mittel",
                        max_length=100,
                        verbose_name="Kondition",
                    ),
                ),
                ("equipment", models.TextField(blank=True, verbose_name="Ausrüstung")),
                (
                    "eventart",
                    models.CharField(
                        choices=[
                            ("Einzeltermin", "Einzeltermin"),
                            ("Mehrtagesevent", "Mehrtagesevent"),
                            ("Regelmäßiges Event/Training", "Regelmäßiges Event/Training"),
                            ("Tagesevent", "Tagesevent"),
                            ("Wochenendevent", "Wochenendevent"),
                        ],
                        default="Einzeltermin",
                        max_length=100,
                        verbose_name="Eventart",
                    ),
                ),
                (
                    "klassifizierung",
                    models.CharField(
                        choices=[
                            ("Gemeinschaftstour", "Gemeinschaftstour"),
                            ("Ausbildung", "Ausbildung"),
                        ],
                        default="Gemeinschaftstour",
                        max_length=100,
                        verbose_name="Klassifizierung",
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Max. Teilnehmerzahl",
                    ),
                ),
                (
                    "saison",
                    models.CharField(
                        choices=[
                            ("ganzjährig", "ganzjährig"),
                            ("Indoor", "Indoor"),
                            ("Sommer", "Sommer"),
                            ("Winter", "Winter"),
                        ],
                        default="ganzjährig",
                        max_length=100,
                        verbose_name="Saison",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=100, verbose_name="Untertitel"),
                ),
                (
                    "technik",
                    models.CharField(
                        choices=[
                            ("leicht", "leicht"),
                            ("mittel", "mittel"),
                            ("schwer", "schwer"),
                            ("sehr schwer", "sehr schwer"),
                        ],
                        default="mittel",
                        max_length=100,
                        verbose_name="Technik",
                    ),
                ),
                ("voraussetzungen", models.TextField(blank=True, verbose_name="Voraussetzungen")),
            ],
            options={
                "verbose_name_plural": "Termine",
                "verbose_name": "Termin",
            },
        ),
    ]
