# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludwigsburgalpin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='description',
            field=models.TextField(default='', verbose_name='Tourenbeschreibung/Anforderung'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termin',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termin',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefonnumer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termin',
            name='responsible',
            field=models.CharField(default='', max_length=100, verbose_name='Organisator'),
            preserve_default=False,
        ),
    ]
