# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-26 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludwigsburgalpin', '0002_auto_20190926_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tourenbeschreibung/Anforderung'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='group',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Gruppe'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefonnumer'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, verbose_name='Organisator'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
