# Generated by Django 4.0.1 on 2022-01-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludwigsburgalpin', '0004_alter_termin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
