# Generated by Django 4.0.1 on 2022-09-20 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludwigsburgalpin', '0005_alter_termin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='anforderung_dauer',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Etappendauer in Stunden'),
        ),
        migrations.AddField(
            model_name='termin',
            name='anforderung_hoehe',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Höhenmeter in Meter'),
        ),
        migrations.AddField(
            model_name='termin',
            name='anforderung_strecke',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Strecke in Kilometer'),
        ),
        migrations.AddField(
            model_name='termin',
            name='category',
            field=models.CharField(choices=[('WAN', 'Wandern'), ('BW', 'Bergwandern'), ('KST', 'Klettersteig'), ('KL', 'Klettern'), ('SKI', 'Piste, Loipe'), ('SCH', 'Schneeschuhgehen'), ('ST', 'Skitour'), ('STH', 'Skihochtour'), ('HT', 'Hochtour'), ('MTB', 'Montainbike'), ('AUS', 'Ausbildung'), ('SON', 'Sonstiges z.B. Treffen')], default='SON', max_length=100, verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='termin',
            name='condition',
            field=models.CharField(choices=[('gering', 'gering'), ('mittel', 'mittel'), ('groß', 'groß'), ('sehr groß', 'sehr groß')], default='mittel', max_length=100, verbose_name='Kondition'),
        ),
        migrations.AddField(
            model_name='termin',
            name='equipment',
            field=models.TextField(blank=True, verbose_name='Ausrüstung'),
        ),
        migrations.AddField(
            model_name='termin',
            name='eventart',
            field=models.CharField(choices=[('Einzeltermin', 'Einzeltermin'), ('Mehrtagesevent', 'Mehrtagesevent'), ('Regelmäßiges Event/Training', 'Regelmäßiges Event/Training'), ('Tagesevent', 'Tagesevent'), ('Wochenendevent', 'Wochenendevent')], default='Einzeltermin', max_length=100, verbose_name='Eventart'),
        ),
        migrations.AddField(
            model_name='termin',
            name='klassifizierung',
            field=models.CharField(choices=[('Gemeinschaftstour', 'Gemeinschaftstour'), ('Ausbildung', 'Ausbildung')], default='Gemeinschaftstour', max_length=100, verbose_name='Klassifizierung'),
        ),
        migrations.AddField(
            model_name='termin',
            name='max_participants',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max. Teilnehmerzahl'),
        ),
        migrations.AddField(
            model_name='termin',
            name='saison',
            field=models.CharField(choices=[('ganzjährig', 'ganzjährig'), ('Indoor', 'Indoor'), ('Sommer', 'Sommer'), ('Winter', 'Winter')], default='ganzjährig', max_length=100, verbose_name='Saison'),
        ),
        migrations.AddField(
            model_name='termin',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Untertitel'),
        ),
        migrations.AddField(
            model_name='termin',
            name='technik',
            field=models.CharField(choices=[('leicht', 'leicht'), ('mittel', 'mittel'), ('schwer', 'schwer'), ('sehr schwer', 'sehr schwer')], default='mittel', max_length=100, verbose_name='Technik'),
        ),
        migrations.AddField(
            model_name='termin',
            name='voraussetzungen',
            field=models.TextField(blank=True, verbose_name='Voraussetzungen'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='group',
            field=models.CharField(choices=[('ASG', 'Alpinsportgruppe'), ('OGB', 'Ortsgruppe Bietigheim'), ('OGV', 'Ortsgruppe Vaihingen'), ('JUG', 'Jugend'), ('FAM', 'Familen'), ('Ü30', 'Ü30'), ('MTB', 'Mountainbike'), ('RA', 'RegioAktiv'), ('SEK', 'Sektion')], max_length=100, verbose_name='Gruppe'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='responsible',
            field=models.CharField(max_length=100, verbose_name='Organisator'),
        ),
    ]
