# Generated by Django 4.0.1 on 2023-03-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludwigsburgalpin', '0006_termin_anforderung_dauer_termin_anforderung_hoehe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='group',
            field=models.CharField(choices=[('ASG', 'Alpinsportgruppe'), ('OGB', 'Ortsgruppe Bietigheim'), ('OGV', 'Ortsgruppe Vaihingen'), ('JUG', 'Jugend'), ('FAM', 'Familie'), ('Ü30', 'Ü30'), ('MTB', 'Mountainbike'), ('RA', 'RegioAktiv'), ('SEK', 'Sektion')], max_length=100, verbose_name='Gruppe'),
        ),
    ]
