# Generated by Django 5.1.15 on 2026-09-20 23:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Spell ``KATEGORIE``'s MTB label "Mountainbike", as ``GRUPPE`` already does.

    Metadata only: ``choices`` is not part of a CharField's ``db_parameters``,
    so this alters no column and touches no stored row. Only the label the
    admin and the API's ``/enums`` render for the unchanged ``MTB`` value.
    """

    dependencies = [
        ("ludwigsburgalpin", "0001_initial_squashed_0007_alter_termin_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termin",
            name="category",
            field=models.CharField(
                choices=[
                    ("WAN", "Wandern"),
                    ("BW", "Bergwandern"),
                    ("KST", "Klettersteig"),
                    ("KL", "Klettern"),
                    ("SKI", "Piste, Loipe"),
                    ("SCH", "Schneeschuhgehen"),
                    ("ST", "Skitour"),
                    ("STH", "Skihochtour"),
                    ("HT", "Hochtour"),
                    ("MTB", "Mountainbike"),
                    ("AUS", "Ausbildung"),
                    ("SON", "Sonstiges z.B. Treffen"),
                ],
                default="SON",
                max_length=100,
                verbose_name="Kategorie",
            ),
        ),
    ]
