"""
Django settings for jdav_web project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

from split_settings.tools import optional, include
import os

base_settings = [
    'local.py',
    'components/base.py',
    'components/database.py',
    'components/cache.py',
    'components/jet.py',
    'components/emails.py',
    'components/texts.py',
    'components/locale.py',
]

include(*base_settings)
