# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpart',
            name='buy_date',
            field=models.DateField(verbose_name='purchase date'),
        ),
    ]
