# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Material category',
                'verbose_name_plural': 'Material categories',
            },
        ),
        migrations.AddField(
            model_name='materialpart',
            name='material_cat',
            field=models.ManyToManyField(default=None, to='material.MaterialCategory', verbose_name='Material category'),
        ),
    ]
