# Generated by Django 4.0.1 on 2024-11-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='show_in_navigation',
            field=models.BooleanField(default=True, verbose_name='Show in navigation'),
        ),
    ]
