# Generated by Django 4.0.1 on 2024-11-23 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0002_section_show_in_navigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='startpage.section', verbose_name='section'),
        ),
    ]
