# Generated by Django 4.0.1 on 2025-02-25 12:20

import utils
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("startpage", "0003_alter_post_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "icon",
                    utils.RestrictedFileField(
                        blank=True, upload_to="icons", verbose_name="Link Icon"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Description"),
                ),
                ("url", models.URLField(max_length=250)),
                ("visible", models.BooleanField(default=True, verbose_name="Visible")),
            ],
            options={
                "verbose_name": "Link",
                "verbose_name_plural": "Links",
            },
        ),
    ]
