# Generated by Django 4.0.1

from django.db import migrations


def add_kompass_documentation_link(apps, schema_editor):
    Link = apps.get_model("startpage", "Link")
    Link.objects.get_or_create(
        url="/static/docs/",
        defaults={
            "title": "Anleitung zur Benutzung des Kompasses",
            "description": "Kompass Dokumentation",
            "visible": True,
        },
    )


def remove_kompass_documentation_link(apps, schema_editor):  # pragma: no cover
    Link = apps.get_model("startpage", "Link")
    Link.objects.filter(url="/static/docs/").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("startpage", "0004_internal_startpage_links"),
    ]

    operations = [
        migrations.RunPython(add_kompass_documentation_link, remove_kompass_documentation_link),
    ]
