# Generated by Django 5.1.15 on 2026-05-03 18:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("startpage", "0005_add_kompass_documentation_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Answer")),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
    ]
