# Generated by Django 5.1.15 on 2026-09-14 20:51

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0048_group_website_display_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Received on")),
                ("page_url", models.CharField(blank=True, max_length=500, verbose_name="Page")),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=300, verbose_name="Browser"),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="members.member",
                        verbose_name="Submitted by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedback",
                "ordering": ["-created"],
            },
        ),
    ]
