# Generated by Django 4.0.1 on 2024-11-23 21:15

import django.contrib.auth.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=100, verbose_name="Password")),
            ],
        ),
        migrations.CreateModel(
            name="AuthGroup",
            fields=[],
            options={
                "verbose_name": "Permission group",
                "verbose_name_plural": "Permission groups",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="LoginDatum",
            fields=[],
            options={
                "verbose_name": "Login Datum",
                "verbose_name_plural": "Login Data",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
