# Generated by Django 4.0.1 on 2024-11-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logindata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationpassword',
            options={'verbose_name': 'Active registration password', 'verbose_name_plural': 'Active registration passwords'},
        ),
    ]
