# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('min_age', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prename', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Group')),
            ],
        ),
    ]
