# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('min_age', models.IntegerField(default=5, verbose_name='minimum age (years)')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Klettertreff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='Date')),
                ('location', models.CharField(default='', max_length=60, verbose_name='Location')),
                ('topic', models.CharField(default='', max_length=60, verbose_name='Topic')),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='members.Group')),
            ],
            options={
                'verbose_name': 'Klettertreff',
                'verbose_name_plural': 'Klettertreffs',
            },
        ),
        migrations.CreateModel(
            name='KlettertreffAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klettertreff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Klettertreff')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prename', models.CharField(max_length=20, verbose_name='prename')),
                ('lastname', models.CharField(max_length=20, verbose_name='last name')),
                ('street', models.CharField(blank=True, default='', max_length=30, verbose_name='street')),
                ('town', models.CharField(blank=True, default='', max_length=30, verbose_name='town')),
                ('phone_number', models.CharField(blank=True, default='', max_length=12, verbose_name='phone number')),
                ('phone_number_parents', models.CharField(blank=True, default='', max_length=12, verbose_name='parents phone number')),
                ('email', models.EmailField(default='', max_length=100)),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('gets_newsletter', models.BooleanField(default=True, verbose_name='receives newsletter')),
                ('unsubscribe_key', models.CharField(default='', max_length=32)),
                ('unsubscribe_expire', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True, default='', verbose_name='comments')),
                ('created', models.DateField(auto_now=True, verbose_name='created')),
                ('queue', models.BooleanField(default=False, verbose_name='queue')),
                ('registration_form', models.ImageField(blank=True, upload_to='', verbose_name='registration form')),
                ('group', models.ManyToManyField(to='members.Group', verbose_name='group')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
        migrations.CreateModel(
            name='MemberList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Activity')),
                ('place', models.CharField(default='', max_length=50, verbose_name='Place')),
                ('destination', models.CharField(blank=True, default='', max_length=50, verbose_name='Destination (optional)')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('end', models.DateField(blank=True, default=datetime.datetime.today, verbose_name='End (optional)')),
                ('tour_type', multiselectfield.db.fields.MultiSelectField(choices=[('Gemeinschaftstour', 'Gemeinschaftstour'), ('Führungstour', 'Führungstour'), ('Ausbildung', 'Ausbildung')], default='', max_length=41)),
                ('difficulty', models.IntegerField(choices=[(1, 'easy'), (2, 'medium'), (3, 'hard')], verbose_name='Difficulty')),
                ('activity', models.ManyToManyField(default=None, to='members.ActivityCategory')),
                ('groups', models.ManyToManyField(to='members.Group')),
                ('jugendleiter', models.ManyToManyField(to='members.Member')),
            ],
            options={
                'verbose_name': 'Memberlist',
                'verbose_name_plural': 'Memberlists',
            },
        ),
        migrations.CreateModel(
            name='MemberOnList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='Member')),
                ('memberlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.MemberList')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.AddField(
            model_name='klettertreffattendee',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='klettertreff',
            name='jugendleiter',
            field=models.ManyToManyField(to='members.Member'),
        ),
    ]
