# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('min_age', models.IntegerField(default=5, verbose_name='minimum age (years)')),
            ],
            options={
                'verbose_name_plural': 'groups',
                'verbose_name': 'group',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prename', models.CharField(max_length=20, verbose_name='prename')),
                ('lastname', models.CharField(max_length=20, verbose_name='last name')),
                ('email', models.EmailField(default='', max_length=100)),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('group', models.ManyToManyField(to='members.Group')),
            ],
            options={
                'verbose_name_plural': 'members',
                'verbose_name': 'member',
            },
        ),
        migrations.CreateModel(
            name='MemberList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='List Name')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('add_member', models.ManyToManyField(to='members.Member')),
            ],
        ),
    ]
