# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlist',
            name='tour_type',
            field=models.IntegerField(choices=[(0, 'Gemeinschaftstour'), (1, 'Führungstour'), (2, 'Ausbildung')], verbose_name='Art der Tour'),
        ),
    ]
