# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
