# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170704_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_parents',
            field=models.EmailField(blank=True, default='', max_length=100, verbose_name="Parents' Email"),
        ),
        migrations.AlterField(
            model_name='klettertreff',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='members.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='memberlist',
            name='activity',
            field=models.ManyToManyField(default=None, to='members.ActivityCategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='memberlist',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='memberlist',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'easy'), (2, 'medium'), (3, 'hard')]),
        ),
        migrations.AlterField(
            model_name='memberlist',
            name='groups',
            field=models.ManyToManyField(to='members.Group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='memberlist',
            name='tour_type',
            field=models.IntegerField(choices=[(0, 'Gemeinschaftstour'), (1, 'Führungstour'), (2, 'Ausbildung')]),
        ),
    ]
