# Generated by Django 4.0.1 on 2023-04-01 04:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_remove_member_not_waiting_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="member",
            name="address_extra",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Address extra"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="allergies",
            field=models.CharField(default="", max_length=100, verbose_name="Allergies"),
        ),
        migrations.AddField(
            model_name="member",
            name="civil_status",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Civil status"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="country",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Country"),
        ),
        migrations.AddField(
            model_name="member",
            name="dav_badge_no",
            field=models.CharField(default="", max_length=20, verbose_name="DAV badge number"),
        ),
        migrations.AddField(
            model_name="member",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Gender"),
        ),
        migrations.AddField(
            model_name="member",
            name="has_free_ticket_gym",
            field=models.BooleanField(
                default=False, verbose_name="Has a free ticket for the climbing gym"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="has_key",
            field=models.BooleanField(default=False, verbose_name="Has key"),
        ),
        migrations.AddField(
            model_name="member",
            name="legal_guardians",
            field=models.CharField(default="", max_length=100, verbose_name="Legal guardians"),
        ),
        migrations.AddField(
            model_name="member",
            name="medication",
            field=models.CharField(default="", max_length=100, verbose_name="Medication"),
        ),
        migrations.AddField(
            model_name="member",
            name="nationality",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Nationality"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="rock_experience",
            field=models.CharField(default="", max_length=50, verbose_name="Rock experience"),
        ),
        migrations.AddField(
            model_name="member",
            name="swimming_badge",
            field=models.CharField(default="", max_length=20, verbose_name="Swimming badge"),
        ),
        migrations.AddField(
            model_name="member",
            name="technical_comments",
            field=models.TextField(blank=True, default="", verbose_name="Technical comments"),
        ),
        migrations.AddField(
            model_name="member",
            name="tetanus_vaccination",
            field=models.CharField(default="", max_length=50, verbose_name="Tetanus vaccination"),
        ),
        migrations.AddField(
            model_name="member",
            name="join_date",
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Joined on"),
        ),
        migrations.AddField(
            model_name="member",
            name="leave_date",
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Left on"),
        ),
        migrations.AddField(
            model_name="member",
            name="good_conduct_certificate_presented_date",
            field=models.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Good conduct certificate presented on",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="birth date"),
        ),
        migrations.AlterField(
            model_name="memberwaitinglist",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="birth date"),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone_number_parents",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="parents phone number"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone_number_parents",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="parents phone number"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="phone_number_mobile",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="phone number mobile"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone_number_parents",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="parents phone number"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="phone_number_private",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="phone number private"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="climbing_badge",
            field=models.CharField(default="", max_length=100, verbose_name="Climbing badge"),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="member",
            name="photos_may_be_taken",
            field=models.BooleanField(default=False, verbose_name="Photos may be taken"),
        ),
        migrations.AddField(
            model_name="member",
            name="good_conduct_certificate_presentation_needed",
            field=models.BooleanField(
                default=False, verbose_name="Good conduct certificate presentation needed"
            ),
        ),
    ]
