# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
