# Generated by Django 4.0.1 on 2023-04-01 06:02

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_adapt_to_clubdesk_contact_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("permission_needed", models.BooleanField(verbose_name="Permission needed")),
            ],
            options={
                "verbose_name": "Training category",
                "verbose_name_plural": "Training categories",
            },
        ),
        migrations.AlterField(
            model_name="member",
            name="allergies",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Allergies"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="climbing_badge",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Climbing badge"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="dav_badge_no",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="DAV badge number"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="legal_guardians",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Legal guardians"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="medication",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Medication"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="rock_experience",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Rock experience"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="swimming_badge",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Swimming badge"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="tetanus_vaccination",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Tetanus vaccination"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="birth date"),
        ),
        migrations.CreateModel(
            name="MemberTraining",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                ("title", models.CharField(max_length=30, verbose_name="Title")),
                ("comments", models.TextField(blank=True, verbose_name="Comments")),
                ("participated", models.BooleanField(verbose_name="Participated")),
                ("passed", models.BooleanField(verbose_name="Passed")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traininigs",
                        to="members.member",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.trainingcategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training",
                "verbose_name_plural": "Trainings",
            },
        ),
        migrations.AlterField(
            model_name="memberwaitinglist",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="birth date"),
        ),
    ]
