# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20161018_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.ManyToManyField(to='members.Group'),
        ),
    ]
