# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20170712_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='queue',
        ),
        migrations.AddField(
            model_name='member',
            name='plz',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Postcode'),
        ),
        migrations.AddField(
            model_name='member',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Registration complete'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number_parents',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='parents phone number'),
        ),
    ]
