# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-15 10:24
from __future__ import unicode_literals

from django.db import migrations
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20171011_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='registration_form',
            field=utils.RestrictedFileField(blank=True, upload_to='registration_forms', verbose_name='registration form'),
        ),
    ]
