# Generated by Django 4.0.1 on 2023-04-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_add_training_data_alter_required_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldmemberonlist',
            name='member',
        ),
        migrations.RemoveField(
            model_name='oldmemberonlist',
            name='memberlist',
        ),
        migrations.DeleteModel(
            name='MemberList',
        ),
        migrations.DeleteModel(
            name='OldMemberOnList',
        ),
    ]
