# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-14 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20190615_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': (('may_see_qualities', 'Is allowed to see the quality overview'),), 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
    ]
