# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-24 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('members', '0006_auto_20190914_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freizeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Activity')),
                ('place', models.CharField(default='', max_length=50, verbose_name='Place')),
                ('destination', models.CharField(blank=True, default='', max_length=50, verbose_name='Destination (optional)')),
                ('date', models.DateField(default=datetime.datetime.today, verbose_name='Date')),
                ('end', models.DateField(blank=True, default=datetime.datetime.today, verbose_name='End (optional)')),
                ('tour_type', models.IntegerField(choices=[(0, 'Gemeinschaftstour'), (1, 'Führungstour'), (2, 'Ausbildung')])),
                ('difficulty', models.IntegerField(choices=[(1, 'easy'), (2, 'medium'), (3, 'hard')])),
                ('activity', models.ManyToManyField(default=None, to='members.ActivityCategory', verbose_name='Categories')),
                ('groups', models.ManyToManyField(to='members.Group', verbose_name='Groups')),
                ('jugendleiter', models.ManyToManyField(to='members.Member')),
            ],
            options={
                'verbose_name_plural': 'Freizeiten',
                'verbose_name': 'Freizeit',
            },
        ),
        migrations.CreateModel(
            name='MemberNoteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Title')),
                ('date', models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='Date')),
            ],
            options={
                'verbose_name_plural': 'Notizlisten',
                'verbose_name': 'Notizliste',
            },
        ),
        migrations.CreateModel(
            name='NewMemberOnList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('comments', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('content_type', models.ForeignKey(default='members', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='Member')),
            ],
            options={
                'verbose_name_plural': 'Members',
                'verbose_name': 'Member',
            },
        ),
        migrations.RenameModel(
            old_name='MemberOnList',
            new_name='OldMemberOnList',
        ),
    ]
