# Generated by Django 4.0.1 on 2023-04-03 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0006_rename_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="freizeit",
            options={"verbose_name": "Freizeit", "verbose_name_plural": "Freizeiten"},
        ),
        migrations.AlterModelOptions(
            name="member",
            options={
                "permissions": (
                    ("may_see_qualities", "Is allowed to see the quality overview"),
                    ("may_set_auth_user", "Is allowed to set auth user member connections."),
                    ("change_member_group", "Can change the group field"),
                ),
                "verbose_name": "member",
                "verbose_name_plural": "members",
            },
        ),
        migrations.AlterModelOptions(
            name="membertraining",
            options={"verbose_name": "Training", "verbose_name_plural": "Trainings"},
        ),
    ]
