# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-24 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200924_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='member',
            name='not_waiting',
            field=models.BooleanField(default=True, verbose_name='Not waiting'),
        ),
    ]
