# Generated by Django 4.0.1 on 2022-01-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20210924_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cc_email_parents',
            field=models.BooleanField(default=True, verbose_name='Also send mails to parents'),
        )
    ]
