# Generated by Django 4.0.1 on 2023-04-04 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_create_default_permission_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freizeit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Begin'),
        ),
        migrations.AlterField(
            model_name='freizeit',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End (optional)'),
        ),
    ]
