# Generated by Django 4.0.1 on 2022-09-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_activitycategory_id_alter_freizeit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freizeit',
            name='tour_approach',
            field=models.IntegerField(choices=[(0, 'Muskelkraft'), (1, 'Öffentliche VM'), (2, 'Fahrgemeinschaften')], default=0),
        ),
    ]
