# Generated by Django 4.0.1 on 2023-04-09 11:46

import utils
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0011_alter_freizeit_date_alter_freizeit_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AddField(
            model_name="group",
            name="show_website",
            field=models.BooleanField(default=False, verbose_name="show on website"),
        ),
        migrations.AddField(
            model_name="member",
            name="image",
            field=utils.RestrictedFileField(blank=True, upload_to="people", verbose_name="image"),
        ),
    ]
