# Generated by Django 4.0.1 on 2022-10-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_freizeit_tour_approach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='min_age',
        ),
        migrations.AddField(
            model_name='group',
            name='year_from',
            field=models.IntegerField(default=2010, verbose_name='lowest year'),
        ),
        migrations.AddField(
            model_name='group',
            name='year_to',
            field=models.IntegerField(default=2011, verbose_name='highest year'),
        ),
    ]
