# Generated by Django 4.0.1 on 2022-10-02 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_group_min_age_group_year_from_group_year_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='echo_expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='member',
            name='echo_key',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='member',
            name='echoed',
            field=models.BooleanField(default=True, verbose_name='Echoed'),
        ),
    ]
