# Generated by Django 4.0.1 on 2023-09-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_member_image_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberwaitinglist',
            name='application_text',
            field=models.TextField(blank=True, default='', verbose_name='application text'),
        ),
        migrations.AddField(
            model_name='memberwaitinglist',
            name='application_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='application date'),
        ),
    ]
