# Generated by Django 4.0.1 on 2022-10-03 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_member_echo_expire_member_echo_key_member_echoed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberUnconfirmedProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Unconfirmed registration',
                'verbose_name_plural': 'Unconfirmed registrations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('members.member',),
        ),
        migrations.AddField(
            model_name='member',
            name='confirm_mail_key',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='member',
            name='confirm_mail_parents_key',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='member',
            name='confirmed',
            field=models.BooleanField(default=True, verbose_name='Confirmed'),
        ),
        migrations.AddField(
            model_name='member',
            name='confirmed_mail',
            field=models.BooleanField(default=True, verbose_name='Email confirmed'),
        ),
        migrations.AddField(
            model_name='member',
            name='confirmed_mail_parents',
            field=models.BooleanField(default=True, verbose_name='Parents email confirmed'),
        ),
        migrations.CreateModel(
            name='RegistrationPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='', max_length=20, unique=True, verbose_name='Password')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.group')),
            ],
            options={
                'verbose_name': 'registration password',
                'verbose_name_plural': 'registration passwords',
            },
        ),
    ]
