# Generated by Django 4.0.1 on 2024-10-13 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_memberwaitinglist_add_application_text_and_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='member',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='member',
            name='rock_experience',
        ),
        migrations.RemoveField(
            model_name='member',
            name='technical_comments',
        ),
        migrations.AddField(
            model_name='member',
            name='alpine_experience',
            field=models.TextField(blank=True, default='', verbose_name='Alpine experience'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Männlich'), (1, 'Weiblich'), (2, 'Divers')], default=2, verbose_name='Gender'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='swimming_badge',
        ),
        migrations.AddField(
            model_name='member',
            name='swimming_badge',
            field=models.BooleanField(default=False, verbose_name='Knows how to swim'),
        ),
        migrations.RenameField(
            model_name='member',
            old_name='confirm_mail_parents_key',
            new_name='confirm_alternative_mail_key',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cc_email_parents',
        ),
        migrations.RemoveField(
            model_name='member',
            name='confirmed_mail_parents',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email_parents',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_number_mobile',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_number_parents',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_number_private',
        ),
        migrations.RemoveField(
            model_name='memberwaitinglist',
            name='cc_email_parents',
        ),
        migrations.RemoveField(
            model_name='memberwaitinglist',
            name='confirm_mail_parents_key',
        ),
        migrations.RemoveField(
            model_name='memberwaitinglist',
            name='confirmed_mail_parents',
        ),
        migrations.RemoveField(
            model_name='memberwaitinglist',
            name='email_parents',
        ),
        migrations.AddField(
            model_name='member',
            name='alternative_email',
            field=models.EmailField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='confirmed_alternative_mail',
            field=models.BooleanField(default=True, verbose_name='Alternative email confirmed'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(default='', max_length=100, verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='Member')),
                ('confirm_mail_key', models.CharField(default='', max_length=32)),
                ('confirmed_mail', models.BooleanField(default=True, verbose_name='Email confirmed')),
                ('email', models.EmailField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=20, verbose_name='last name')),
                ('phone_number', models.CharField(default='', max_length=100, verbose_name='phone number')),
                ('prename', models.CharField(default='', max_length=20, verbose_name='prename')),
            ],
            options={
                'verbose_name': 'Emergency contact',
                'verbose_name_plural': 'Emergency contacts',
                'abstract': False,
                'default_permissions': ('add_global', 'change_global', 'view_global', 'delete_global', 'list_global', 'view'),
            },
            bases=(models.Model, rules.contrib.models.RulesModelMixin),
        ),
        migrations.AlterField(
            model_name='memberwaitinglist',
            name='application_text',
            field=models.TextField(blank=True, default='', verbose_name='Do you want to tell us something else?'),
        ),
        migrations.AddField(
            model_name='memberwaitinglist',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Männlich'), (1, 'Weiblich'), (2, 'Divers')], default=2, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='memberwaitinglist',
            name='application_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='application date'),
            preserve_default=False,
        ),
    ]
