# Generated by Django 4.0.1 on 2024-10-13 19:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0014_remove_fields_alternative_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontact",
            name="lastname",
            field=models.CharField(max_length=20, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="phone_number",
            field=models.CharField(max_length=100, verbose_name="phone number"),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="prename",
            field=models.CharField(max_length=20, verbose_name="prename"),
        ),
    ]
