# Generated by Django 4.0.1 on 2022-10-06 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0014_memberunconfirmedproxy_member_confirm_mail_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': (('may_see_qualities', 'Is allowed to see the quality overview'), ('may_set_auth_user', 'Is allowed to set auth user member connections.')), 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
        migrations.AlterModelOptions(
            name='memberunconfirmedproxy',
            options={'permissions': (('may_manage_all_registrations', 'Can view and manage all unconfirmed registrations.'),), 'verbose_name': 'Unconfirmed registration', 'verbose_name_plural': 'Unconfirmed registrations'},
        ),
        migrations.AddField(
            model_name='group',
            name='leiters',
            field=models.ManyToManyField(blank=True, related_name='leited_groups', to='members.Member', verbose_name='youth leaders'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='street',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='street and house number'),
        ),
    ]
