# Generated by Django 4.0.1 on 2024-10-15 21:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0015_alter_emergencycontact_lastname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontact",
            name="confirmed_mail",
            field=models.BooleanField(default=False, verbose_name="Email confirmed"),
        ),
        migrations.AlterField(
            model_name="member",
            name="confirmed_mail",
            field=models.BooleanField(default=False, verbose_name="Email confirmed"),
        ),
        migrations.AlterField(
            model_name="memberwaitinglist",
            name="confirmed_mail",
            field=models.BooleanField(default=False, verbose_name="Email confirmed"),
        ),
    ]
