# Generated by Django 4.0.1 on 2024-10-15 21:22

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0016_alter_emergencycontact_confirmed_mail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="alternative_email",
            field=models.EmailField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
