# Generated by Django 4.0.1 on 2024-10-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_member_alternative_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ending time'),
        ),
        migrations.AddField(
            model_name='group',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Starting time'),
        ),
        migrations.AddField(
            model_name='group',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
    ]
