# Generated by Django 4.0.1 on 2024-10-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_group_add_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberwaitinglist',
            name='last_reminder',
            field=models.DateTimeField(auto_now=True, verbose_name='Last reminder'),
        ),
        migrations.AddField(
            model_name='memberwaitinglist',
            name='sent_reminders',
            field=models.IntegerField(default=0, verbose_name='Missed reminders'),
        ),
    ]
