# Generated by Django 4.0.1 on 2024-11-17 15:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0019_memberwaitinglist_last_reminder_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="freizeit",
            options={
                "default_permissions": (
                    "add_global",
                    "change_global",
                    "view_global",
                    "delete_global",
                    "list_global",
                    "view",
                ),
                "verbose_name": "Excursion",
                "verbose_name_plural": "Excursions",
            },
        ),
        migrations.AddField(
            model_name="freizeit",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="freizeit",
            name="destination",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. a peak",
                max_length=50,
                verbose_name="Destination (optional)",
            ),
        ),
    ]
