# Generated by Django 4.0.1 on 2024-11-17 21:32

import django.db.models.deletion
import members.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0020_alter_freizeit_options_freizeit_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationToGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(auto_now=True, verbose_name="Invitation date")),
                (
                    "rejected",
                    models.BooleanField(default=False, verbose_name="Invitation rejected"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.group",
                        verbose_name="Group",
                    ),
                ),
                (
                    "waiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.memberwaitinglist",
                        verbose_name="Waiter",
                    ),
                ),
                ("key", models.CharField(default=members.models.gen_key, max_length=32)),
            ],
            options={
                "verbose_name": "Invitation to group",
                "verbose_name_plural": "Invitations to groups",
            },
        ),
        migrations.RemoveField(
            model_name="memberwaitinglist",
            name="invited_for_group",
        ),
    ]
