# Generated by Django 4.0.1 on 2024-11-18 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_group_invitations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='good_conduct_certificate_presentation_needed',
        ),
        migrations.AlterField(
            model_name='member',
            name='allergies',
            field=models.TextField(blank=True, default='', verbose_name='Allergies'),
        ),
        migrations.AlterField(
            model_name='member',
            name='medication',
            field=models.TextField(blank=True, default='', verbose_name='Medication'),
        ),
        migrations.AddField(
            model_name='member',
            name='may_cancel_appointment_independently',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='May cancel a group appointment independently'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='memberwaitinglist',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='application date'),
        ),
    ]
