# Generated by Django 4.0.1 on 2024-11-23 19:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0023_alter_member_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="invite_as_user_key",
            field=models.CharField(default="", max_length=32),
        ),
    ]
