# Generated by Django 4.0.1 on 2024-11-24 19:08

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0025_alter_member_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencycontact",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=100),
        ),
    ]
