# Generated by Django 4.0.1 on 2024-11-27 22:16

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0026_alter_emergencycontact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="weekday",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                null=True,
                verbose_name="week day",
            ),
        ),
    ]
