# Generated by Django 4.0.1 on 2024-11-27 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_alter_emailaddress_name'),
        ('members', '0027_alter_group_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='contact_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.emailaddress', verbose_name='Contact email'),
        ),
    ]
