# Generated by Django 4.0.1 on 2024-11-28 00:16

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0028_group_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="gender",
            field=models.IntegerField(
                choices=[(0, "Männlich"), (1, "Weiblich"), (2, "Divers")], verbose_name="Gender"
            ),
        ),
        migrations.AlterField(
            model_name="memberwaitinglist",
            name="gender",
            field=models.IntegerField(
                choices=[(0, "Männlich"), (1, "Weiblich"), (2, "Divers")], verbose_name="Gender"
            ),
        ),
    ]
