# Generated by Django 4.0.1 on 2024-12-02 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_alter_member_gender_alter_memberwaitinglist_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'default_permissions': ('add_global', 'change_global', 'view_global', 'delete_global', 'list_global', 'view'), 'permissions': (('may_see_qualities', 'Is allowed to see the quality overview'), ('may_set_auth_user', 'Is allowed to set auth user member connections.'), ('may_change_member_group', 'Can change the group field'), ('may_invite_as_user', 'Is allowed to invite a member to set login data.'), ('may_change_organizationals', 'Is allowed to set organizational settings on members.')), 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
    ]
