# Generated by Django 4.0.1 on 2024-12-15 18:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0030_alter_member_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="waitinglist_application_date",
            field=models.DateTimeField(
                blank=True,
                help_text="If the person registered from the waitinglist, this is their application date.",
                null=True,
                verbose_name="waitinglist application date",
            ),
        ),
    ]
