# Generated by Django 4.0.1 on 2024-12-15 22:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0031_member_waitinglist_application_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="upload_registration_form_key",
            field=models.CharField(default="", max_length=32),
        ),
    ]
