# Generated by Django 4.0.1 on 2025-01-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_member_upload_registration_form_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='freizeit',
            name='approved_extra_youth_leader_count',
            field=models.PositiveIntegerField(default=0, help_text='The number of approved youth leaders per excursion is determined by the number of participants. In special circumstances, e.g. in case of a technically demanding excursion, more youth leaders may be approved.', verbose_name='Number of additional approved youth leaders'),
        ),
    ]
