# Generated by Django 4.0.1 on 2025-02-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_freizeit_approved_extra_youth_leader_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycategory',
            name='ljp_category',
            field=models.CharField(choices=[('Winter', 'winter'), ('Skibergsteigen', 'ski mountaineering'), ('Klettern', 'climbing'), ('Bergsteigen', 'mountaineering'), ('Theorie', 'theory'), ('Sonstiges', 'others')], help_text='The official category for LJP applications associated with this activity.', max_length=20, verbose_name='LJP category'),
        ),
    ]
