# Generated by Django 4.0.1 on 2025-02-06 21:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0034_activitycategory_ljp_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ljpproposal",
            name="evaluation",
        ),
        migrations.RemoveField(
            model_name="ljpproposal",
            name="experiences",
        ),
        migrations.RemoveField(
            model_name="ljpproposal",
            name="goals_alpinistic",
        ),
        migrations.RemoveField(
            model_name="ljpproposal",
            name="goals_pedagogic",
        ),
        migrations.RemoveField(
            model_name="ljpproposal",
            name="methods",
        ),
        migrations.AddField(
            model_name="ljpproposal",
            name="goal",
            field=models.IntegerField(
                choices=[
                    (1, "Qualification"),
                    (2, "Participation"),
                    (3, "Personality development"),
                    (4, "Environment"),
                ],
                default=1,
                help_text="Official learning goal according to LJP regulations.",
                verbose_name="Learning goal",
            ),
        ),
        migrations.AddField(
            model_name="ljpproposal",
            name="goal_strategy",
            field=models.TextField(
                blank=True,
                default="",
                help_text="How do you want to reach the learning goal? Has the goal been reached? If not, why not? If yes, what helped you to reach the goal?",
                verbose_name="Strategy",
            ),
        ),
        migrations.AlterField(
            model_name="ljpproposal",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Official title of your seminar, this can differ from the informal title. Use e.g. sports climbing course instead of climbing weekend for fun.",
                max_length=30,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="ljpproposal",
            name="category",
            field=models.IntegerField(
                choices=[(2, "Educational programme"), (1, "Staff training")],
                default=2,
                help_text="Type of seminar. Usually the correct choice is educational programme.",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="ljpproposal",
            name="not_bw_reason",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Course content"),
                    (2, "Available rooms"),
                    (3, "Close to the border"),
                    (4, "Economic reasons"),
                ],
                default=None,
                help_text="If the excursion takes place outside of Baden-Württemberg, please explain. Otherwise, leave this empty.",
                null=True,
                verbose_name="Explanation if excursion not in Baden-Württemberg",
            ),
        ),
        migrations.AlterField(
            model_name="ljpproposal",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Official title of your seminar, this can differ from the informal title. Use e.g. sports climbing course instead of climbing weekend for fun.",
                max_length=100,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="freizeit",
            name="postcode",
            field=models.CharField(default="", max_length=30, verbose_name="Postcode"),
        ),
    ]
