# Generated by Django 4.0.1 on 2025-02-07 23:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0035_ljp_application_rework"),
    ]

    operations = [
        migrations.AddField(
            model_name="freizeit",
            name="approval_comments",
            field=models.TextField(blank=True, default="", verbose_name="Approval comments"),
        ),
        migrations.AddField(
            model_name="freizeit",
            name="approved",
            field=models.BooleanField(
                default=None,
                help_text="Choose no in case of rejection or yes in case of approval. Leave empty, if not yet decided.",
                null=True,
                verbose_name="Approved",
            ),
        ),
        migrations.AlterModelOptions(
            name="freizeit",
            options={
                "default_permissions": (
                    "add_global",
                    "change_global",
                    "view_global",
                    "delete_global",
                    "list_global",
                    "view",
                ),
                "permissions": (
                    ("manage_approval_excursion", "Can edit the approval status of excursions."),
                    ("view_approval_excursion", "Can view the approval status of excursions."),
                ),
                "verbose_name": "Excursion",
                "verbose_name_plural": "Excursions",
            },
        ),
    ]
