# Generated by Django 4.0.1 on 2025-02-11 22:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0036_excursion_add_approval_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberwaitinglist",
            name="leave_key",
            field=models.CharField(default="", max_length=32),
        ),
    ]
