# Generated by Django 4.0.1 on 2025-02-22 21:59

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0037_memberwaitinglist_leave_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationtogroup",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Invitation date"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="created",
            field=models.DateField(default=django.utils.timezone.now, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="memberwaitinglist",
            name="last_reminder",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Last reminder"
            ),
        ),
        migrations.AlterField(
            model_name="memberwaitinglist",
            name="last_wait_confirmation",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Last wait confirmation"
            ),
        ),
    ]
