# Generated by Django 4.0.1 on 2025-02-25 06:34

import utils
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0038_alter_invitationtogroup_date_alter_member_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membertraining",
            name="certificate",
            field=utils.RestrictedFileField(
                blank=True, upload_to="training_forms", verbose_name="certificate of attendance"
            ),
        ),
    ]
