# Generated by Django 4.2.20 on 2025-04-06 11:30

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0039_membertraining_certificate_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationtogroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_group_invitations",
                to="members.member",
                verbose_name="Created by",
            ),
        ),
    ]
