# Generated by Django 4.2.20 on 2025-06-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_invitationtogroup_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ticket_no',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='entrance ticket number'),
        ),
    ]
