# Generated by Django 4.2.20 on 2025-05-03 15:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0040_invitationtogroup_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="freizeit",
            name="crisis_intervention_list_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="freizeit",
            name="notification_crisis_intervention_list_sent",
            field=models.BooleanField(default=False),
        ),
    ]
