# Generated by Django 4.2.20 on 2025-06-22 11:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0041_freizeit_crisis_intervention_list_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="ticket_no",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="entrance ticket number"
            ),
        ),
    ]
