# Generated by Django 4.2.20 on 2025-06-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0042_member_ticket_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertraining',
            name='activity',
            field=models.ManyToManyField(to='members.activitycategory', verbose_name='Activity'),
        ),
    ]
