# Generated by Django 4.2.20 on 2025-10-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0043_waitinglist_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertraining',
            name='activity',
            field=models.ManyToManyField(to='members.activitycategory', verbose_name='Activity'),
        ),
        migrations.AlterModelOptions(
            name='membertraining',
            options={'default_permissions': ('add_global', 'change_global', 'view_global', 'delete_global', 'list_global', 'view'), 'permissions': (('manage_success_trainings', 'Can edit the success status of trainings.'),), 'verbose_name': 'Training', 'verbose_name_plural': 'Trainings'},
        ),
        migrations.AlterField(
            model_name='membertraining',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
