# Generated by Django 4.2.20 on 2025-08-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0043_membertraining_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membertraining',
            options={'default_permissions': ('add_global', 'change_global', 'view_global', 'delete_global', 'list_global', 'view'), 'permissions': (('manage_success_trainings', 'Can edit the success status of trainings.'),), 'verbose_name': 'Training', 'verbose_name_plural': 'Trainings'},
        ),
    ]
