# Generated by Django 4.2.20 on 2025-10-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0044_alter_membertraining_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertraining',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
