# Generated by Django 4.2.20 on 2025-12-29 09:16

import django.db.models.deletion
import rules.contrib.models
import utils
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0045_statement_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invitationtogroup",
            options={
                "default_permissions": (
                    "add_global",
                    "change_global",
                    "view_global",
                    "delete_global",
                    "list_global",
                    "view",
                ),
                "verbose_name": "Invitation to group",
                "verbose_name_plural": "Invitations to groups",
            },
        ),
        migrations.CreateModel(
            name="MemberDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("f", utils.RestrictedFileField(upload_to="member_documents", verbose_name="file")),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.member"
                    ),
                ),
            ],
            options={
                "verbose_name": "member document",
                "verbose_name_plural": "member documents",
            },
            bases=(models.Model, rules.contrib.models.RulesModelMixin),
        ),
    ]
