# Generated by Django 4.2.20 on 2025-12-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0046_memberdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitationtogroup',
            options={'default_permissions': ('add_global', 'change_global', 'view_global', 'delete_global', 'list_global', 'view'), 'verbose_name': 'Invitation to group', 'verbose_name_plural': 'Invitations to groups'},
        ),
        migrations.AddField(
            model_name='membernotelist',
            name='date_end',
            field=models.DateField(blank=True, help_text='End date for multi-day activities', null=True, verbose_name='End date (optional)'),
        ),
        migrations.AddField(
            model_name='membernotelist',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Additional information about the activity', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='membernotelist',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Location of the activity (for crisis intervention lists)', max_length=100, verbose_name='Location'),
        ),
    ]
