# Generated by Django 4.2.20 on 2026-01-17 22:38

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0046_memberdocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freizeit",
            name="postcode",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Postcode"),
        ),
        migrations.AlterField(
            model_name="freizeit",
            name="kilometers_traveled",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Kilometers traveled",
            ),
        ),
    ]
