# Generated by Django 4.2 on 2026-04-26 00:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0047_alter_excursion_field_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="ljpproposal",
            name="methods",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Describe the methods used in the seminar. Which didactic and methodical approaches were applied?",
                verbose_name="Methods",
            ),
        ),
        migrations.AddField(
            model_name="ljpproposal",
            name="pedagogical_goals",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Describe the pedagogical goals of the seminar. Which educational objectives were pursued and how were they implemented?",
                verbose_name="Pedagogical goals",
            ),
        ),
        migrations.AddField(
            model_name="ljpproposal",
            name="alpine_goals",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Describe the alpine sports goals of the seminar. Which alpine sports content was taught and what skill level was aimed for?",
                verbose_name="Alpine sports goals",
            ),
        ),
    ]
